#!/bin/bash
set -e

# build apt cache
apt-get update

# install build dependencies
apt-get install -y gcc make libc6-dev ruby-dev python-dev libmysqlclient-dev libpq-dev libyaml-dev

# install mysql2psql
gem install --no-document mysql2psql

# install py-mysql2pgsql
pip install py-mysql2pgsql

# purge build dependencies
apt-get purge -y --auto-remove gcc make libc6-dev ruby-dev python-dev libmysqlclient-dev libpq-dev libyaml-dev

# clean up
rm -rf /var/lib/apt/lists/*
